status: wip
default: archived
variants:
- name: archived
  context:
    type: archived
    content: "<p>This is archived.</p><ul><li>Can</li><li>have</li><li>arbitrary HTML</li><li>still looks OK.</li></ul>"
- name: draft
  context:
    type: draft
    content: "<p>This is archived.</p><ul><li>Can</li><li>have</li><li>arbitrary HTML</li><li>still looks OK.</li></ul>"
- name: translation
  context:
    type: translation
    content: '<h2 class="visuallyhidden">Über diese Übersetzung</h2><p>Diese ehrenamtliche Übersetzung spiegelt möglicherweise nicht genau die Absichten des <a href="/wai-website/videos/standards-and-benefits/">englischen Originals</a> wider.</p><p><svg aria-hidden="true" class="icon-warning "><use xlink:href="/wai-website/assets/images/icons.svg#icon-warning"></use></svg> Englische Version aktualisiert seit dieser Übersetzung: <a href="">Änderungsprotokoll</a>. <br>Englisch aktualisiert: 20 Feb 2019. Übersetzung aktualisiert: 28 Jan 2019.</p><p><strong>Übersetzung:</strong> Sandra Kallmeyer. Mitwirkende(r): Stefanie Hegele. WAI dankt diesen Übersetzerinnen und Übersetzern und begrüßt weitere <a href="/wai-website/about/translating/">Übersetzungen</a>.</p>'
